# Project information
site_name: "Today I Learned"
site_description: "Today I Learned"
site_author: "Dale-Kurt Murray"
site_url: "https://til.dalekurtmurray.com/"

# Repository
repo_name: "dalekurt/til"
repo_url: https://github.com/dalekurt/til
edit_uri: "edit/main/docs/"

# Copyright
copyright: "Copyright &copy;"

# Navigation

theme:
  name: material
  custom_dir: overrides
  # logo: _files/logo.png
  # favicon: _files/favicon.svg
  icon:
    repo: fontawesome/brands/github-alt

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
    # - navigation.sections
    - navigation.tabs
    - navigation.tracking
    # - navigation.sections
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
docs_dir: ./docs

# extra_css:
# - _static/custom.css

# Plugins
plugins:
- search
- git-revision-date-localized
- minify:
    minify_html: true

# Customization
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/dalekurt
  - icon: fontawesome/brands/instagram
    link: https://instagram.com/dalekurt
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/dalekurt
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/r/dalekurt
  analytics:
    provider: google
    property: G-

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.keys
  - mkdocs_graphviz
  - footnotes

# Page tree

nav:
  - Home: index.md
  - Kubernetes:
    - How to remove nodes: kubernetes/remove-a-kubernetes-node.md
  - Linux:
    - Update hostname: linux: update-hostname.md
  - Python: 
    - Resources: python/resources.md
  - Go: 
    - Resources: go/resources.md
  - Git:
    - Create empty branch on GitHub: git/create-empty-branch-on-github.md
  - GitHub Actions:
    - How to deploy MkDocs to GitHub Pages: github-actions/how-to-deploy-mkdocs-gh-pages.md
