# Project information
site_name: "Today I Learned"
site_description: "Today I Learned"
site_author: "Dale-Kurt Murray"
site_url: "https://til.dalekurtmurray.com/"

# Repository
repo_name: "dalekurt/til"
repo_url: https://github.com/dalekurt/til
edit_uri: "edit/main/docs/"

# Copyright
copyright: "Copyright &copy;"

# Navigation

theme:
  name: material
  custom_dir: overrides
  # logo: _files/logo.png
  # favicon: _files/favicon.svg
  icon:
    repo: fontawesome/brands/github-alt

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
    # - navigation.sections
    - navigation.tabs
    - navigation.tracking
    # - navigation.sections
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
docs_dir: ./docs

# extra_css:
# - _static/custom.css

# Plugins
plugins:
- search
- minify:
    minify_html: true

# Customization
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/dalekurt
  - icon: fontawesome/brands/instagram
    link: https://instagram.com/dalekurt
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/dalekurt
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/r/dalekurt

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - codehilite:
      guess_lang: true
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dalekurt
      repo: til
  - pymdownx.mark
  - pymdownx.smartsymbols
  # - pymdownx.superfences:
  #     highlight_code: true
  #     custom_fences:
  #     - name: mermaid
  #       class: mermaid-experimental
  #       format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # - mkdocs_markdown_graphviz

# Page tree

nav:
  - Home: index.md
