name: Lint Code Base

on:
  pull_request:
    branches: [main]

jobs:
  markdownlint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install markdownlint-cli
      - run: $(npm bin)/markdownlint docs README.md
