name: publish
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Create requirements.txt
        run: poetry export -f requirements.txt --without-hashes | sed 's/-e //' >> /tmp/requirements.txt
      - name: Install Dependencies
        run: pip install --no-cache-dir -r /tmp/requirements.txt
      - name: Deploy GithHub Pages
        run: mkdocs gh-deploy --force
